import { loadMatchScoreCsv } from "../parse-final-points";
import type { MatchScoreGroup, MatchScoreSheet } from "../types";

/**
 * UEFA Champions League 2026/27 (competition_id 4) — match score sheets (active — register new UCL matches here).
 * CSVs live in data/competitions/uefa-cl-2026-27/match-scores/. `groupStageGw` = ordinal matchweek.
 */
export const UCL_2026_27 = "uefa-cl-2026-27";

export const UCL_MATCH_SCORE_SHEETS: MatchScoreSheet[] = [
  {
    slug: "aek-athens-lask",
    title: "AEK Athens vs LASK",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106404,
    rows: loadMatchScoreCsv("AEKAthens_LASK_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "club-brugge-aston-villa",
    title: "Club Brugge vs Aston Villa",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106295,
    rows: loadMatchScoreCsv("ClubBrugge_AstonVilla_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "borussia-dortmund-villarreal",
    title: "Borussia Dortmund vs Villarreal",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106272,
    rows: loadMatchScoreCsv("BorussiaDortmund_Villarreal_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "fc-porto-manchester-city",
    title: "FC Porto vs Manchester City",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106286,
    rows: loadMatchScoreCsv("FCPorto_ManchesterCity_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "lille-real-betis",
    title: "Lille vs Real Betis",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106311,
    rows: loadMatchScoreCsv("Lille_RealBetis_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "real-madrid-inter",
    title: "Real Madrid vs Inter",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106242,
    rows: loadMatchScoreCsv("RealMadrid_Inter_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "barcelona-feyenoord",
    title: "Barcelona vs Feyenoord",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106264,
    rows: loadMatchScoreCsv("Barcelona_Feyenoord_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "vfb-stuttgart-viking",
    title: "VfB Stuttgart vs Viking",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106400,
    rows: loadMatchScoreCsv("VfBStuttgart_Viking_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "liverpool-atletico-madrid",
    title: "Liverpool vs Atlético Madrid",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106246,
    rows: loadMatchScoreCsv("Liverpool_AtlticoMadrid_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "paris-saint-germain-slovan-bratislava",
    title: "Paris Saint-Germain vs Slovan Bratislava",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106237,
    rows: loadMatchScoreCsv("ParisSaintGermain_SlovanBratislava_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "sporting-cp-galatasaray",
    title: "Sporting CP vs Galatasaray",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106280,
    rows: loadMatchScoreCsv("SportingCP_Galatasaray_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "napoli-arsenal",
    title: "Napoli vs Arsenal",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106318,
    rows: loadMatchScoreCsv("Napoli_Arsenal_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "fenerbahce-roma",
    title: "Fenerbahçe vs Roma",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106331,
    rows: loadMatchScoreCsv("Fenerbahe_Roma_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "psv-eindhoven-shakhtar-donetsk",
    title: "PSV Eindhoven vs Shakhtar Donetsk",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106304,
    rows: loadMatchScoreCsv("PSVEindhoven_ShakhtarDonetsk_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "bayern-munich-bodo-glimt",
    title: "Bayern München vs Bodø/Glimt",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106240,
    rows: loadMatchScoreCsv("BayernMnchen_BodGlimt_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "como-rb-leipzig",
    title: "Como vs RB Leipzig",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106411,
    rows: loadMatchScoreCsv("Como_RBLeipzig_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "manchester-united-sabah-fk",
    title: "Manchester United vs Sabah FK",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106293,
    rows: loadMatchScoreCsv("ManchesterUnited_SabahFK_FinalPoints.csv", UCL_2026_27),
  },
  {
    slug: "slavia-prague-lens",
    title: "Slavia Prague vs Lens",
    subtitle: "UEFA Champions League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: UCL_2026_27,
    fotmobMatchId: 6106392,
    rows: loadMatchScoreCsv("SlaviaPrague_Lens_FinalPoints.csv", UCL_2026_27),
  },
];

export const UCL_MATCH_SCORE_GROUPS: MatchScoreGroup[] = [
  {
    gw: 1,
    label: "UEFA Champions League GW1",
    sheets: UCL_MATCH_SCORE_SHEETS.filter((s) => s.groupStageGw === 1),
  },
];
