import { loadMatchScoreCsv } from "../parse-final-points";
import type { MatchScoreGroup, MatchScoreSheet } from "../types";

/**
 * English Premier League 2026/27 (competition_id 2) — match score sheets (archived Oct 2026; kept so auction 9 pages keep working).
 * CSVs live in data/competitions/epl-2026-27/match-scores/. `groupStageGw` = ordinal matchweek.
 */
export const EPL_2026_27 = "epl-2026-27";

export const EPL_MATCH_SCORE_SHEETS: MatchScoreSheet[] = [
  {
    slug: "arsenal-coventry-city",
    title: "Arsenal vs Coventry City",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795363,
    rows: loadMatchScoreCsv("Arsenal_CoventryCity_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "hull-city-manchester-united",
    title: "Hull City vs Manchester United",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795364,
    rows: loadMatchScoreCsv("HullCity_ManchesterUnited_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "ipswich-town-sunderland",
    title: "Ipswich Town vs Sunderland",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795366,
    rows: loadMatchScoreCsv("IpswichTown_Sunderland_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "everton-crystal-palace",
    title: "Everton vs Crystal Palace",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795365,
    rows: loadMatchScoreCsv("Everton_CrystalPalace_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "leeds-nottingham-forest",
    title: "Leeds United vs Nottingham Forest",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795367,
    rows: loadMatchScoreCsv("NottinghamForest_LeedsUnited_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "brentford-tottenham-hotspur",
    title: "Brentford vs Tottenham Hotspur",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795368,
    rows: loadMatchScoreCsv("Brentford_TottenhamHotspur_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "brighton-aston-villa",
    title: "Brighton & Hove Albion vs Aston Villa",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795369,
    rows: loadMatchScoreCsv("BrightonHoveAlbion_AstonVilla_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "manchester-city-afc-bournemouth",
    title: "Manchester City vs AFC Bournemouth",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795370,
    rows: loadMatchScoreCsv("ManchesterCity_AFCBournemouth_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "liverpool-newcastle-united",
    title: "Newcastle United vs Liverpool",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795371,
    rows: loadMatchScoreCsv("NewcastleUnited_Liverpool_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "chelsea-fulham",
    title: "Fulham vs Chelsea",
    subtitle: "Premier League · Matchweek 1",
    groupStageGw: 1,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795372,
    rows: loadMatchScoreCsv("Fulham_Chelsea_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "crystal-palace-manchester-city",
    title: "Crystal Palace vs Manchester City",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795429,
    rows: loadMatchScoreCsv("CrystalPalace_ManchesterCity_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "liverpool-nottingham-forest",
    title: "Liverpool vs Nottingham Forest",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795431,
    rows: loadMatchScoreCsv("Liverpool_NottinghamForest_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "afc-bournemouth-everton",
    title: "AFC Bournemouth vs Everton",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795425,
    rows: loadMatchScoreCsv("AFCBournemouth_Everton_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "coventry-city-hull-city",
    title: "Coventry City vs Hull City",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795428,
    rows: loadMatchScoreCsv("CoventryCity_HullCity_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "tottenham-hotspur-newcastle-united",
    title: "Tottenham Hotspur vs Newcastle United",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795434,
    rows: loadMatchScoreCsv("TottenhamHotspur_NewcastleUnited_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "chelsea-brighton-hove-albion",
    title: "Chelsea vs Brighton & Hove Albion",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795427,
    rows: loadMatchScoreCsv("Chelsea_BrightonHoveAlbion_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "leeds-united-brentford",
    title: "Leeds United vs Brentford",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795430,
    rows: loadMatchScoreCsv("LeedsUnited_Brentford_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "sunderland-fulham",
    title: "Sunderland vs Fulham",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795433,
    rows: loadMatchScoreCsv("Sunderland_Fulham_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "manchester-united-ipswich-town",
    title: "Manchester United vs Ipswich Town",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795432,
    rows: loadMatchScoreCsv("ManchesterUnited_IpswichTown_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "aston-villa-arsenal",
    title: "Aston Villa vs Arsenal",
    subtitle: "Premier League · Matchweek 2",
    groupStageGw: 2,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795426,
    rows: loadMatchScoreCsv("AstonVilla_Arsenal_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "ipswich-town-liverpool",
    title: "Ipswich Town vs Liverpool",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795441,
    rows: loadMatchScoreCsv("IpswichTown_Liverpool_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "newcastle-united-afc-bournemouth",
    title: "Newcastle United vs AFC Bournemouth",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795443,
    rows: loadMatchScoreCsv("NewcastleUnited_AFCBournemouth_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "brentford-sunderland",
    title: "Brentford vs Sunderland",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795436,
    rows: loadMatchScoreCsv("Brentford_Sunderland_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "brighton-leeds-united",
    title: "Brighton & Hove Albion vs Leeds United",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795437,
    rows: loadMatchScoreCsv("BrightonHoveAlbion_LeedsUnited_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "fulham-crystal-palace",
    title: "Fulham vs Crystal Palace",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795439,
    rows: loadMatchScoreCsv("Fulham_CrystalPalace_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "manchester-city-coventry-city",
    title: "Manchester City vs Coventry City",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795442,
    rows: loadMatchScoreCsv("ManchesterCity_CoventryCity_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "nottingham-forest-tottenham-hotspur",
    title: "Nottingham Forest vs Tottenham Hotspur",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795444,
    rows: loadMatchScoreCsv("NottinghamForest_TottenhamHotspur_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "hull-city-aston-villa",
    title: "Hull City vs Aston Villa",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795440,
    rows: loadMatchScoreCsv("HullCity_AstonVilla_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "everton-manchester-united",
    title: "Everton vs Manchester United",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795438,
    rows: loadMatchScoreCsv("Everton_ManchesterUnited_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "arsenal-chelsea",
    title: "Arsenal vs Chelsea",
    subtitle: "Premier League · Matchweek 3",
    groupStageGw: 3,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795435,
    rows: loadMatchScoreCsv("Arsenal_Chelsea_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "afc-bournemouth-brentford",
    title: "AFC Bournemouth vs Brentford",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795445,
    rows: loadMatchScoreCsv("AFCBournemouth_Brentford_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "aston-villa-nottingham-forest",
    title: "Aston Villa vs Nottingham Forest",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795446,
    rows: loadMatchScoreCsv("AstonVilla_NottinghamForest_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "chelsea-hull-city",
    title: "Chelsea vs Hull City",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795447,
    rows: loadMatchScoreCsv("Chelsea_HullCity_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "crystal-palace-ipswich-town",
    title: "Crystal Palace vs Ipswich Town",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795449,
    rows: loadMatchScoreCsv("CrystalPalace_IpswichTown_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "liverpool-fulham",
    title: "Liverpool vs Fulham",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795451,
    rows: loadMatchScoreCsv("Liverpool_Fulham_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "tottenham-hotspur-everton",
    title: "Tottenham Hotspur vs Everton",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795454,
    rows: loadMatchScoreCsv("TottenhamHotspur_Everton_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "sunderland-arsenal",
    title: "Sunderland vs Arsenal",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795453,
    rows: loadMatchScoreCsv("Sunderland_Arsenal_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "coventry-city-brighton-hove-albion",
    title: "Coventry City vs Brighton & Hove Albion",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795448,
    rows: loadMatchScoreCsv("CoventryCity_BrightonHoveAlbion_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "manchester-united-manchester-city",
    title: "Manchester United vs Manchester City",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795452,
    rows: loadMatchScoreCsv("ManchesterUnited_ManchesterCity_FinalPoints.csv", EPL_2026_27),
  },
  {
    slug: "leeds-united-newcastle-united",
    title: "Leeds United vs Newcastle United",
    subtitle: "Premier League · Matchweek 4",
    groupStageGw: 4,
    competitionSlug: EPL_2026_27,
    fotmobMatchId: 5795450,
    rows: loadMatchScoreCsv("LeedsUnited_NewcastleUnited_FinalPoints.csv", EPL_2026_27),
  },
];

export const EPL_MATCH_SCORE_GROUPS: MatchScoreGroup[] = [
  {
    gw: 1,
    label: "Premier League GW1",
    sheets: EPL_MATCH_SCORE_SHEETS.filter((s) => s.groupStageGw === 1),
  },
  {
    gw: 2,
    label: "Premier League GW2",
    sheets: EPL_MATCH_SCORE_SHEETS.filter((s) => s.groupStageGw === 2),
  },
  {
    gw: 3,
    label: "Premier League GW3",
    sheets: EPL_MATCH_SCORE_SHEETS.filter((s) => s.groupStageGw === 3),
  },
  {
    gw: 4,
    label: "Premier League GW4",
    sheets: EPL_MATCH_SCORE_SHEETS.filter((s) => s.groupStageGw === 4),
  },
];
