import { loadMatchScoreCsv } from "../parse-final-points";
import type { MatchScoreGroup, MatchScoreSheet } from "../types";

/**
 * FIFA World Cup 2026 (competition_id 1) — match score sheets (archived; auctions 5/6/7).
 * CSVs live in data/competitions/world-cup-2026/match-scores/. These are the scores the app
 * showed during the tournament (they match every published Best XI); the post-tournament
 * GW1 re-score under competitions/archive/world-cup-2026/records/ was never published.
 * `groupStageGw` = World Cup gameweek, which is also its legacy game_week_id (1–8).
 */
export const WC_2026 = "world-cup-2026";

export const WC_MATCH_SCORE_SHEETS: MatchScoreSheet[] = [
  {
    slug: "mexico-south-africa",
    title: "Mexico vs South Africa",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Mexico_SouthAfrica_FinalPoints.csv", WC_2026),
  },
  {
    slug: "south-korea-czechia",
    title: "South Korea vs Czechia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("SouthKorea_Czechia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "canada-bosnia-herzegovina",
    title: "Canada vs Bosnia and Herzegovina",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Canada_BosniaandHerzegovina_FinalPoints.csv", WC_2026),
  },
  {
    slug: "usa-paraguay",
    title: "USA vs Paraguay",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("USA_Paraguay_FinalPoints.csv", WC_2026),
  },
  {
    slug: "qatar-switzerland",
    title: "Qatar vs Switzerland",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Qatar_Switzerland_FinalPoints.csv", WC_2026),
  },
  {
    slug: "brazil-morocco",
    title: "Brazil vs Morocco",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Brazil_Morocco_FinalPoints.csv", WC_2026),
  },
  {
    slug: "haiti-scotland",
    title: "Haiti vs Scotland",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Haiti_Scotland_FinalPoints.csv", WC_2026),
  },
  {
    slug: "australia-turkiye",
    title: "Australia vs Turkiye",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Australia_Turkiye_FinalPoints.csv", WC_2026),
  },
  {
    slug: "germany-curacao",
    title: "Germany vs Curacao",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Germany_Curacao_FinalPoints.csv", WC_2026),
  },
  {
    slug: "netherlands-japan",
    title: "Netherlands vs Japan",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Netherlands_Japan_FinalPoints.csv", WC_2026),
  },
  {
    slug: "ivory-coast-ecuador",
    title: "Ivory Coast vs Ecuador",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("IvoryCoast_Ecuador_FinalPoints.csv", WC_2026),
  },
  {
    slug: "sweden-tunisia",
    title: "Sweden vs Tunisia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Sweden_Tunisia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "cape-verde-spain",
    title: "Cape Verde vs Spain",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Spain_CapeVerde_FinalPoints.csv", WC_2026),
  },
  {
    slug: "belgium-egypt",
    title: "Belgium vs Egypt",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Belgium_Egypt_FinalPoints.csv", WC_2026),
  },
  {
    slug: "saudi-arabia-uruguay",
    title: "Saudi Arabia vs Uruguay",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("SaudiArabia_Uruguay_FinalPoints.csv", WC_2026),
  },
  {
    slug: "iran-new-zealand",
    title: "Iran vs New Zealand",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Iran_NewZealand_FinalPoints.csv", WC_2026),
  },
  {
    slug: "france-senegal",
    title: "France vs Senegal",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("France_Senegal_FinalPoints.csv", WC_2026),
  },
  {
    slug: "iraq-norway",
    title: "Iraq vs Norway",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Iraq_Norway_FinalPoints.csv", WC_2026),
  },
  {
    slug: "argentina-algeria",
    title: "Argentina vs Algeria",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Argentina_Algeria_FinalPoints.csv", WC_2026),
  },
  {
    slug: "austria-jordan",
    title: "Austria vs Jordan",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Austria_Jordan_FinalPoints.csv", WC_2026),
  },
  {
    slug: "portugal-dr-congo",
    title: "Portugal vs DR Congo",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Portugal_DRCongo_FinalPoints.csv", WC_2026),
  },
  {
    slug: "england-croatia",
    title: "England vs Croatia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("England_Croatia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "ghana-panama",
    title: "Ghana vs Panama",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Ghana_Panama_FinalPoints.csv", WC_2026),
  },
  {
    slug: "uzbekistan-colombia",
    title: "Uzbekistan vs Colombia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Uzbekistan_Colombia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "czechia-south-africa",
    title: "Czechia vs South Africa",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Czechia_SouthAfrica_FinalPoints.csv", WC_2026),
  },
  {
    slug: "switzerland-bosnia-herzegovina",
    title: "Switzerland vs Bosnia and Herzegovina",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Switzerland_BosniaandHerzegovina_FinalPoints.csv", WC_2026),
  },
  {
    slug: "canada-qatar",
    title: "Canada vs Qatar",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Canada_Qatar_FinalPoints.csv", WC_2026),
  },
  {
    slug: "mexico-south-korea",
    title: "Mexico vs South Korea",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Mexico_SouthKorea_FinalPoints.csv", WC_2026),
  },
  {
    slug: "usa-australia",
    title: "USA vs Australia",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("USA_Australia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "scotland-morocco",
    title: "Scotland vs Morocco",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Scotland_Morocco_FinalPoints.csv", WC_2026),
  },
  {
    slug: "brazil-haiti",
    title: "Brazil vs Haiti",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Brazil_Haiti_FinalPoints.csv", WC_2026),
  },
  {
    slug: "turkiye-paraguay",
    title: "Turkiye vs Paraguay",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Turkiye_Paraguay_FinalPoints.csv", WC_2026),
  },
  {
    slug: "netherlands-sweden",
    title: "Netherlands vs Sweden",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Netherlands_Sweden_FinalPoints.csv", WC_2026),
  },
  {
    slug: "germany-ivory-coast",
    title: "Germany vs Ivory Coast",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Germany_IvoryCoast_FinalPoints.csv", WC_2026),
  },
  {
    slug: "ecuador-curacao",
    title: "Ecuador vs Curacao",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Ecuador_Curacao_FinalPoints.csv", WC_2026),
  },
  {
    slug: "tunisia-japan",
    title: "Tunisia vs Japan",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Tunisia_Japan_FinalPoints.csv", WC_2026),
  },
  {
    slug: "spain-saudi-arabia",
    title: "Spain vs Saudi Arabia",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Spain_SaudiArabia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "belgium-iran",
    title: "Belgium vs Iran",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Belgium_Iran_FinalPoints.csv", WC_2026),
  },
  {
    slug: "uruguay-cape-verde",
    title: "Uruguay vs Cape Verde",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Uruguay_CapeVerde_FinalPoints.csv", WC_2026),
  },
  {
    slug: "new-zealand-egypt",
    title: "New Zealand vs Egypt",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("NewZealand_Egypt_FinalPoints.csv", WC_2026),
  },
  {
    slug: "argentina-austria",
    title: "Argentina vs Austria",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Argentina_Austria_FinalPoints.csv", WC_2026),
  },
  {
    slug: "france-iraq",
    title: "France vs Iraq",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("France_Iraq_FinalPoints.csv", WC_2026),
  },
  {
    slug: "norway-senegal",
    title: "Norway vs Senegal",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Norway_Senegal_FinalPoints.csv", WC_2026),
  },
  {
    slug: "jordan-algeria",
    title: "Jordan vs Algeria",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Jordan_Algeria_FinalPoints.csv", WC_2026),
  },
  {
    slug: "portugal-uzbekistan",
    title: "Portugal vs Uzbekistan",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Portugal_Uzbekistan_FinalPoints.csv", WC_2026),
  },
  {
    slug: "england-ghana",
    title: "England vs Ghana",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("England_Ghana_FinalPoints.csv", WC_2026),
  },
  {
    slug: "panama-croatia",
    title: "Panama vs Croatia",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Panama_Croatia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "colombia-dr-congo",
    title: "Colombia vs DR Congo",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Colombia_DRCongo_FinalPoints.csv", WC_2026),
  },
  {
    slug: "morocco-haiti",
    title: "Morocco vs Haiti",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Morocco_Haiti_FinalPoints.csv", WC_2026),
  },
  {
    slug: "scotland-brazil",
    title: "Brazil vs Scotland",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Scotland_Brazil_FinalPoints.csv", WC_2026),
  },
  {
    slug: "switzerland-canada",
    title: "Switzerland vs Canada",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Switzerland_Canada_FinalPoints.csv", WC_2026),
  },
  {
    slug: "bosnia-herzegovina-qatar",
    title: "Bosnia and Herzegovina vs Qatar",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("BosniaandHerzegovina_Qatar_FinalPoints.csv", WC_2026),
  },
  {
    slug: "czechia-mexico",
    title: "Czechia vs Mexico",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Czechia_Mexico_FinalPoints.csv", WC_2026),
  },
  {
    slug: "south-africa-south-korea",
    title: "South Africa vs South Korea",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("SouthAfrica_SouthKorea_FinalPoints.csv", WC_2026),
  },
  {
    slug: "curacao-ivory-coast",
    title: "Curacao vs Ivory Coast",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Curacao_IvoryCoast_FinalPoints.csv", WC_2026),
  },
  {
    slug: "ecuador-germany",
    title: "Ecuador vs Germany",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Ecuador_Germany_FinalPoints.csv", WC_2026),
  },
  {
    slug: "tunisia-netherlands",
    title: "Tunisia vs Netherlands",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Tunisia_Netherlands_FinalPoints.csv", WC_2026),
  },
  {
    slug: "japan-sweden",
    title: "Japan vs Sweden",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Japan_Sweden_FinalPoints.csv", WC_2026),
  },
  {
    slug: "turkiye-usa",
    title: "Turkiye vs USA",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Turkiye_USA_FinalPoints.csv", WC_2026),
  },
  {
    slug: "paraguay-australia",
    title: "Paraguay vs Australia",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Paraguay_Australia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "norway-france",
    title: "Norway vs France",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Norway_France_FinalPoints.csv", WC_2026),
  },
  {
    slug: "senegal-iraq",
    title: "Senegal vs Iraq",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Senegal_Iraq_FinalPoints.csv", WC_2026),
  },
  {
    slug: "cape-verde-saudi-arabia",
    title: "Cape Verde vs Saudi Arabia",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("CapeVerde_SaudiArabia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "uruguay-spain",
    title: "Uruguay vs Spain",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Uruguay_Spain_FinalPoints.csv", WC_2026),
  },
  {
    slug: "new-zealand-belgium",
    title: "New Zealand vs Belgium",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("NewZealand_Belgium_FinalPoints.csv", WC_2026),
  },
  {
    slug: "egypt-iran",
    title: "Egypt vs Iran",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Egypt_Iran_FinalPoints.csv", WC_2026),
  },
  {
    slug: "panama-england",
    title: "Panama vs England",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Panama_England_FinalPoints.csv", WC_2026),
  },
  {
    slug: "croatia-ghana",
    title: "Croatia vs Ghana",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Croatia_Ghana_FinalPoints.csv", WC_2026),
  },
  {
    slug: "colombia-portugal",
    title: "Colombia vs Portugal",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Colombia_Portugal_FinalPoints.csv", WC_2026),
  },
  {
    slug: "dr-congo-uzbekistan",
    title: "DR Congo vs Uzbekistan",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("DRCongo_Uzbekistan_FinalPoints.csv", WC_2026),
  },
  {
    slug: "algeria-austria",
    title: "Algeria vs Austria",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Algeria_Austria_FinalPoints.csv", WC_2026),
  },
  {
    slug: "jordan-argentina",
    title: "Jordan vs Argentina",
    subtitle: "World Cup 2026 · Group stage · GW3",
    groupStageGw: 3,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Jordan_Argentina_FinalPoints.csv", WC_2026),
  },
  {
    slug: "south-africa-canada",
    title: "South Africa vs Canada",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("SouthAfrica_Canada_FinalPoints.csv", WC_2026),
  },
  {
    slug: "brazil-japan",
    title: "Brazil vs Japan",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Brazil_Japan_FinalPoints.csv", WC_2026),
  },
  {
    slug: "germany-paraguay",
    title: "Germany vs Paraguay",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Germany_Paraguay_FinalPoints.csv", WC_2026),
  },
  {
    slug: "netherlands-morocco",
    title: "Netherlands vs Morocco",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Netherlands_Morocco_FinalPoints.csv", WC_2026),
  },
  {
    slug: "ivory-coast-norway",
    title: "Ivory Coast vs Norway",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("IvoryCoast_Norway_FinalPoints.csv", WC_2026),
  },
  {
    slug: "france-sweden",
    title: "France vs Sweden",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("France_Sweden_FinalPoints.csv", WC_2026),
  },
  {
    slug: "mexico-ecuador",
    title: "Mexico vs Ecuador",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Mexico_Ecuador_FinalPoints.csv", WC_2026),
  },
  {
    slug: "england-drcongo",
    title: "England vs DR Congo",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("England_DRCongo_FinalPoints.csv", WC_2026),
  },
  {
    slug: "belgium-senegal",
    title: "Belgium vs Senegal",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Belgium_Senegal_FinalPoints.csv", WC_2026),
  },
  {
    slug: "usa-bosnia",
    title: "USA vs Bosnia and Herzegovina",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("USA_BosniaandHerzegovina_FinalPoints.csv", WC_2026),
  },
  {
    slug: "spain-austria",
    title: "Spain vs Austria",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Spain_Austria_FinalPoints.csv", WC_2026),
  },
  {
    slug: "portugal-croatia",
    title: "Portugal vs Croatia",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Portugal_Croatia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "switzerland-algeria",
    title: "Switzerland vs Algeria",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Switzerland_Algeria_FinalPoints.csv", WC_2026),
  },
  {
    slug: "australia-egypt",
    title: "Australia vs Egypt",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Australia_Egypt_FinalPoints.csv", WC_2026),
  },
  {
    slug: "argentina-capeverde",
    title: "Argentina vs Cape Verde",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Argentina_CapeVerde_FinalPoints.csv", WC_2026),
  },
  {
    slug: "colombia-ghana",
    title: "Colombia vs Ghana",
    subtitle: "World Cup 2026 · Round of 32",
    groupStageGw: 4,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Colombia_Ghana_FinalPoints.csv", WC_2026),
  },
  {
    slug: "canada-morocco",
    title: "Canada vs Morocco",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Canada_Morocco_FinalPoints.csv", WC_2026),
  },
  {
    slug: "paraguay-france",
    title: "Paraguay vs France",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Paraguay_France_FinalPoints.csv", WC_2026),
  },
  {
    slug: "brazil-norway",
    title: "Brazil vs Norway",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Brazil_Norway_FinalPoints.csv", WC_2026),
  },
  {
    slug: "mexico-england",
    title: "Mexico vs England",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Mexico_England_FinalPoints.csv", WC_2026),
  },
  {
    slug: "portugal-spain",
    title: "Portugal vs Spain",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Portugal_Spain_FinalPoints.csv", WC_2026),
  },
  {
    slug: "usa-belgium",
    title: "USA vs Belgium",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("USA_Belgium_FinalPoints.csv", WC_2026),
  },
  {
    slug: "argentina-egypt",
    title: "Argentina vs Egypt",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Argentina_Egypt_FinalPoints.csv", WC_2026),
  },
  {
    slug: "switzerland-colombia",
    title: "Switzerland vs Colombia",
    subtitle: "World Cup 2026 · Round of 16",
    groupStageGw: 5,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Switzerland_Colombia_FinalPoints.csv", WC_2026),
  },
  {
    slug: "france-morocco",
    title: "France vs Morocco",
    subtitle: "World Cup 2026 · Quarter-finals",
    groupStageGw: 6,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("France_Morocco_FinalPoints.csv", WC_2026),
  },
  {
    slug: "spain-belgium",
    title: "Spain vs Belgium",
    subtitle: "World Cup 2026 · Quarter-finals",
    groupStageGw: 6,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Spain_Belgium_FinalPoints.csv", WC_2026),
  },
  {
    slug: "norway-england",
    title: "Norway vs England",
    subtitle: "World Cup 2026 · Quarter-finals",
    groupStageGw: 6,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Norway_England_FinalPoints.csv", WC_2026),
  },
  {
    slug: "argentina-switzerland",
    title: "Argentina vs Switzerland",
    subtitle: "World Cup 2026 · Quarter-finals",
    groupStageGw: 6,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Argentina_Switzerland_FinalPoints.csv", WC_2026),
  },
  {
    slug: "france-spain",
    title: "France vs Spain",
    subtitle: "World Cup 2026 · Semi-finals",
    groupStageGw: 7,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("France_Spain_FinalPoints.csv", WC_2026),
  },
  {
    slug: "england-argentina",
    title: "England vs Argentina",
    subtitle: "World Cup 2026 · Semi-finals",
    groupStageGw: 7,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("England_Argentina_FinalPoints.csv", WC_2026),
  },
  {
    slug: "spain-argentina",
    title: "Spain vs Argentina",
    subtitle: "World Cup 2026 · Finals",
    groupStageGw: 8,
    competitionSlug: WC_2026,
    rows: loadMatchScoreCsv("Spain_Argentina_FinalPoints.csv", WC_2026),
  },
];

const WC_GROUP_LABELS: Record<number, string> = {
  1: "Group Stage GW1",
  2: "Group Stage GW2",
  3: "Group Stage GW3",
  4: "Round of 32",
  5: "Round of 16",
  6: "Quarter-finals",
  7: "Semi-finals",
  8: "Finals",
};

export const WC_MATCH_SCORE_GROUPS: MatchScoreGroup[] = ([1, 2, 3, 4, 5, 6, 7, 8] as const)
  .map((gw) => ({
    gw,
    label: WC_GROUP_LABELS[gw],
    sheets: WC_MATCH_SCORE_SHEETS.filter((sheet) => sheet.groupStageGw === gw),
  }))
  .filter((group) => group.sheets.length > 0);
