import { loadMatchScoreCsv } from "./parse-final-points";
import type { GroupStageGw, MatchScoreGroup, MatchScoreSheet } from "./types";

export const MATCH_SCORE_SHEETS: MatchScoreSheet[] = [
  {
    slug: "mexico-south-africa",
    title: "Mexico vs South Africa",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Mexico_SouthAfrica_FinalPoints.csv"),
  },
  {
    slug: "south-korea-czechia",
    title: "South Korea vs Czechia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("SouthKorea_Czechia_FinalPoints.csv"),
  },
  {
    slug: "canada-bosnia-herzegovina",
    title: "Canada vs Bosnia and Herzegovina",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Canada_BosniaandHerzegovina_FinalPoints.csv"),
  },
  {
    slug: "usa-paraguay",
    title: "USA vs Paraguay",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("USA_Paraguay_FinalPoints.csv"),
  },
  {
    slug: "qatar-switzerland",
    title: "Qatar vs Switzerland",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Qatar_Switzerland_FinalPoints.csv"),
  },
  {
    slug: "brazil-morocco",
    title: "Brazil vs Morocco",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Brazil_Morocco_FinalPoints.csv"),
  },
  {
    slug: "haiti-scotland",
    title: "Haiti vs Scotland",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Haiti_Scotland_FinalPoints.csv"),
  },
  {
    slug: "australia-turkiye",
    title: "Australia vs Turkiye",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Australia_Turkiye_FinalPoints.csv"),
  },
  {
    slug: "germany-curacao",
    title: "Germany vs Curacao",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Germany_Curacao_FinalPoints.csv"),
  },
  {
    slug: "netherlands-japan",
    title: "Netherlands vs Japan",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Netherlands_Japan_FinalPoints.csv"),
  },
  {
    slug: "ivory-coast-ecuador",
    title: "Ivory Coast vs Ecuador",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("IvoryCoast_Ecuador_FinalPoints.csv"),
  },
  {
    slug: "sweden-tunisia",
    title: "Sweden vs Tunisia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Sweden_Tunisia_FinalPoints.csv"),
  },
  {
    slug: "cape-verde-spain",
    title: "Cape Verde vs Spain",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Spain_CapeVerde_FinalPoints.csv"),
  },
  {
    slug: "belgium-egypt",
    title: "Belgium vs Egypt",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Belgium_Egypt_FinalPoints.csv"),
  },
  {
    slug: "saudi-arabia-uruguay",
    title: "Saudi Arabia vs Uruguay",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("SaudiArabia_Uruguay_FinalPoints.csv"),
  },
  {
    slug: "iran-new-zealand",
    title: "Iran vs New Zealand",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Iran_NewZealand_FinalPoints.csv"),
  },
  {
    slug: "france-senegal",
    title: "France vs Senegal",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("France_Senegal_FinalPoints.csv"),
  },
  {
    slug: "iraq-norway",
    title: "Iraq vs Norway",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Iraq_Norway_FinalPoints.csv"),
  },
  {
    slug: "argentina-algeria",
    title: "Argentina vs Algeria",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Argentina_Algeria_FinalPoints.csv"),
  },
  {
    slug: "austria-jordan",
    title: "Austria vs Jordan",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Austria_Jordan_FinalPoints.csv"),
  },
  {
    slug: "portugal-dr-congo",
    title: "Portugal vs DR Congo",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Portugal_DRCongo_FinalPoints.csv"),
  },
  {
    slug: "england-croatia",
    title: "England vs Croatia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("England_Croatia_FinalPoints.csv"),
  },
  {
    slug: "ghana-panama",
    title: "Ghana vs Panama",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Ghana_Panama_FinalPoints.csv"),
  },
  {
    slug: "uzbekistan-colombia",
    title: "Uzbekistan vs Colombia",
    subtitle: "World Cup 2026 · Group stage · GW1",
    groupStageGw: 1,
    rows: loadMatchScoreCsv("Uzbekistan_Colombia_FinalPoints.csv"),
  },
  {
    slug: "czechia-south-africa",
    title: "Czechia vs South Africa",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Czechia_SouthAfrica_FinalPoints.csv"),
  },
  {
    slug: "switzerland-bosnia-herzegovina",
    title: "Switzerland vs Bosnia and Herzegovina",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Switzerland_BosniaandHerzegovina_FinalPoints.csv"),
  },
  {
    slug: "canada-qatar",
    title: "Canada vs Qatar",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Canada_Qatar_FinalPoints.csv"),
  },
  {
    slug: "mexico-south-korea",
    title: "Mexico vs South Korea",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Mexico_SouthKorea_FinalPoints.csv"),
  },
  {
    slug: "usa-australia",
    title: "USA vs Australia",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("USA_Australia_FinalPoints.csv"),
  },
  {
    slug: "scotland-morocco",
    title: "Scotland vs Morocco",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Scotland_Morocco_FinalPoints.csv"),
  },
  {
    slug: "brazil-haiti",
    title: "Brazil vs Haiti",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Brazil_Haiti_FinalPoints.csv"),
  },
  {
    slug: "turkiye-paraguay",
    title: "Turkiye vs Paraguay",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Turkiye_Paraguay_FinalPoints.csv"),
  },
  {
    slug: "netherlands-sweden",
    title: "Netherlands vs Sweden",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Netherlands_Sweden_FinalPoints.csv"),
  },
  {
    slug: "germany-ivory-coast",
    title: "Germany vs Ivory Coast",
    subtitle: "World Cup 2026 · Group stage · GW2",
    groupStageGw: 2,
    rows: loadMatchScoreCsv("Germany_IvoryCoast_FinalPoints.csv"),
  },
];

const GROUP_LABELS: Record<GroupStageGw, string> = {
  1: "Group Stage GW1",
  2: "Group Stage GW2",
};

export const MATCH_SCORE_GROUPS: MatchScoreGroup[] = ([1, 2] as const).map((gw) => ({
  gw,
  label: GROUP_LABELS[gw],
  sheets: MATCH_SCORE_SHEETS.filter((sheet) => sheet.groupStageGw === gw),
}));

export function getMatchScoreSheet(slug: string): MatchScoreSheet | undefined {
  return MATCH_SCORE_SHEETS.find((s) => s.slug === slug);
}
