-- ════════════════════════════════════════════════════════════════════════════
-- Competition & Auction Data Isolation — schema migration
-- Context: docs/context/COMPETITION_AUCTION_DATA_ISOLATION.md
--
-- Purpose:
--   Make player scores competition-scoped and match-tagged so EPL, Champions
--   League, and World Cup can run/coexist without colliding on a global
--   (player_id, game_week_id) key.
--
-- Safety:
--   Additive and idempotent. New columns are nullable so existing reads/writes
--   keep working during the transition. Run once in the Supabase SQL Editor.
--   No data is dropped.
-- ════════════════════════════════════════════════════════════════════════════

-- ─── 1. Competitions ────────────────────────────────────────────────────────
create table if not exists public.competitions (
  id           bigint generated by default as identity primary key,
  slug         text not null unique,
  name         text not null,
  status       text not null default 'active'
                 check (status in ('active', 'completed', 'archived')),
  archived_at  timestamptz,
  created_at   timestamptz not null default now()
);

-- ─── 2. Competition rounds (a round = one gameweek) ──────────────────────────
create table if not exists public.competition_rounds (
  id                   bigint generated by default as identity primary key,
  competition_id       bigint not null references public.competitions(id) on delete cascade,
  round_slug           text   not null,
  display_name         text,
  round_number         integer,
  status               text   not null default 'open',
  is_active            boolean not null default false,
  -- Transitional bridge to the legacy global Game_Weeks.id (see §13 ID ranges).
  legacy_game_week_id  bigint,
  created_at           timestamptz not null default now(),
  unique (competition_id, round_slug)
);

create index if not exists idx_competition_rounds_competition
  on public.competition_rounds (competition_id);
create index if not exists idx_competition_rounds_legacy_gw
  on public.competition_rounds (legacy_game_week_id);

-- ─── 3. Competition matches (one fixture per team per round) ─────────────────
create table if not exists public.competition_matches (
  id               bigint generated by default as identity primary key,
  competition_id   bigint not null references public.competitions(id) on delete cascade,
  round_id         bigint not null references public.competition_rounds(id) on delete cascade,
  fotmob_match_id  bigint not null,
  match_slug       text,
  home_team        text,
  away_team        text,
  played_at        timestamptz,
  created_at       timestamptz not null default now(),
  unique (competition_id, fotmob_match_id)
);

create index if not exists idx_competition_matches_round
  on public.competition_matches (round_id);

-- ─── 4. Competition players (membership/position within one competition) ─────
create table if not exists public.competition_players (
  competition_id   bigint not null references public.competitions(id) on delete cascade,
  player_id        bigint not null,   -- FotMob player ID
  player_name      text,
  position         text,
  team_id          bigint,
  team_name        text,
  primary key (competition_id, player_id)
);

-- ─── 5. Attach every online auction to exactly one competition ───────────────
alter table public."Auctions"
  add column if not exists competition_id bigint references public.competitions(id);

create index if not exists idx_auctions_competition
  on public."Auctions" (competition_id);

-- ─── 6. Scope + match-tag Player_Scores ──────────────────────────────────────
-- Preferred key is (competition_round_id, player_id). Because a round is a
-- gameweek and every team plays one fixture per round, that pair is unique and
-- the match ID is stored as a traceability attribute (never summed).
alter table public."Player_Scores"
  add column if not exists competition_round_id bigint references public.competition_rounds(id);

alter table public."Player_Scores"
  add column if not exists competition_match_id bigint references public.competition_matches(id);

alter table public."Player_Scores"
  add column if not exists fotmob_match_id bigint;

create index if not exists idx_player_scores_competition_round
  on public."Player_Scores" (competition_round_id);
create index if not exists idx_player_scores_fotmob_match
  on public."Player_Scores" (fotmob_match_id);

-- Once every row is backfilled with competition_round_id, enforce the new key:
--   alter table public."Player_Scores"
--     add constraint player_scores_round_player_unique
--     unique (competition_round_id, player_id);

-- ─── 7. Seed competitions (ids match competitions/**/competition.json) ───────
insert into public.competitions (id, slug, name, status, archived_at)
values
  (1, 'world-cup-2026',   'FIFA World Cup 2026',           'archived', now()),
  (2, 'epl-2026-27',      'English Premier League 2026/27', 'active',   null),
  (3, 'uefa-cl-2025-26',  'UEFA Champions League 2025/26',  'archived', now())
on conflict (slug) do nothing;

-- ─── 8. Seed competition rounds (ids match round.json database_round_id) ─────
insert into public.competition_rounds
  (id, competition_id, round_slug, display_name, round_number, status, is_active, legacy_game_week_id)
values
  -- EPL 2026/27
  (101, 2, 'mw01', 'Matchweek 1', 1, 'open', true, 100),
  -- UEFA Champions League 2025/26 (archived)
  (201, 3, 'ro16-leg2', 'Round of 16, Leg 2',   1, 'archived', false, 200),
  (202, 3, 'qf-leg1',   'Quarter-finals, Leg 1', 2, 'archived', false, 201),
  (203, 3, 'qf-leg2',   'Quarter-finals, Leg 2', 3, 'archived', false, 202),
  (204, 3, 'sf-leg1',   'Semi-finals, Leg 1',    4, 'archived', false, 203),
  (205, 3, 'sf-leg2',   'Semi-finals, Leg 2',    5, 'archived', false, 204)
on conflict (competition_id, round_slug) do nothing;

-- ─── 9. Seed competition matches (FotMob match IDs from match manifests) ─────
insert into public.competition_matches
  (competition_id, round_id, fotmob_match_id, match_slug, home_team, away_team)
values
  -- EPL MW1
  (2, 101, 5795363, 'arsenal-coventry-city',            'Arsenal',            'Coventry City'),
  (2, 101, 5795364, 'hull-city-manchester-united',      'Hull City',          'Manchester United'),
  (2, 101, 5795365, 'everton-crystal-palace',           'Everton',            'Crystal Palace'),
  (2, 101, 5795366, 'ipswich-town-sunderland',          'Ipswich Town',       'Sunderland'),
  (2, 101, 5795367, 'nottingham-forest-leeds-united',   'Nottingham Forest',  'Leeds United'),
  (2, 101, 5795368, 'brentford-tottenham-hotspur',      'Brentford',          'Tottenham Hotspur'),
  -- CL RO16 Leg 2
  (3, 201, 5205731, 'real-madrid-manchester-city',      'Real Madrid',        'Manchester City'),
  (3, 201, 5205734, 'barcelona-newcastle-united',       'Barcelona',          'Newcastle United'),
  (3, 201, 5205738, 'liverpool-galatasaray',            'Liverpool',          'Galatasaray'),
  (3, 201, 5205742, 'tottenham-hotspur-atletico-madrid','Tottenham Hotspur',  'Atletico Madrid'),
  -- CL QF Leg 1
  (3, 202, 5205789, 'paris-saint-germain-liverpool',    'Paris Saint-Germain','Liverpool'),
  (3, 202, 5205791, 'real-madrid-bayern-munich',        'Real Madrid',        'Bayern Munich'),
  (3, 202, 5205793, 'barcelona-atletico-madrid',        'Barcelona',          'Atletico Madrid'),
  (3, 202, 5205795, 'sporting-cp-arsenal',              'Sporting CP',        'Arsenal'),
  -- CL QF Leg 2
  (3, 203, 5205790, 'liverpool-paris-saint-germain',    'Liverpool',          'Paris Saint-Germain'),
  (3, 203, 5205792, 'bayern-munich-real-madrid',        'Bayern Munich',      'Real Madrid'),
  (3, 203, 5205794, 'atletico-madrid-barcelona',        'Atletico Madrid',    'Barcelona'),
  (3, 203, 5205796, 'arsenal-sporting-cp',              'Arsenal',            'Sporting CP'),
  -- CL SF Leg 1
  (3, 204, 5205811, 'paris-saint-germain-bayern-munich','Paris Saint-Germain','Bayern Munich'),
  (3, 204, 5205813, 'atletico-madrid-arsenal',          'Atletico Madrid',    'Arsenal'),
  -- CL SF Leg 2
  (3, 205, 5205812, 'bayern-munich-paris-saint-germain','Bayern Munich',      'Paris Saint-Germain'),
  (3, 205, 5205814, 'arsenal-atletico-madrid',          'Arsenal',            'Atletico Madrid')
on conflict (competition_id, fotmob_match_id) do nothing;

-- ─── 10. Competition-aware upsert (keeps legacy upsert_player_scores intact) ─
-- Pass a JSON array of { "player_id", "score", "fotmob_match_id" }.
-- competition_round_id and competition_match_id are resolved server-side.
create or replace function public.upsert_player_scores_for_round(
  p_competition_round_id bigint,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_upserted integer;
  v_legacy_gw bigint;
begin
  if p_competition_round_id is null then
    raise exception 'p_competition_round_id is required';
  end if;
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    raise exception 'p_rows must be a JSON array';
  end if;

  select legacy_game_week_id into v_legacy_gw
  from public.competition_rounds
  where id = p_competition_round_id;

  if v_legacy_gw is null then
    raise exception 'competition_round % has no legacy_game_week_id; set it before upserting', p_competition_round_id;
  end if;

  insert into public."Player_Scores"
    (player_id, game_week_id, "Score", competition_round_id, competition_match_id, fotmob_match_id)
  select
    (r->>'player_id')::bigint,
    v_legacy_gw,
    (r->>'score')::numeric,
    p_competition_round_id,
    cm.id,
    (r->>'fotmob_match_id')::bigint
  from jsonb_array_elements(p_rows) as r
  left join public.competition_matches cm
    on cm.round_id = p_competition_round_id
   and cm.fotmob_match_id = (r->>'fotmob_match_id')::bigint
  where (r->>'player_id') is not null
    and (r->>'score') is not null
  on conflict (player_id, game_week_id)
  do update set
    "Score"              = excluded."Score",
    competition_round_id = excluded.competition_round_id,
    competition_match_id = excluded.competition_match_id,
    fotmob_match_id      = excluded.fotmob_match_id;

  get diagnostics v_upserted = row_count;

  return jsonb_build_object(
    'competition_round_id', p_competition_round_id,
    'legacy_game_week_id', v_legacy_gw,
    'upserted', v_upserted
  );
end;
$$;

grant execute on function public.upsert_player_scores_for_round(bigint, jsonb) to service_role;

-- ─── 11. Convenience view: scores joined to competition/round/match ──────────
create or replace view public.player_scores_scoped as
select
  ps.id,
  ps.player_id,
  ps."Score"              as score,
  ps.game_week_id,
  ps.competition_round_id,
  cr.round_slug,
  cr.competition_id,
  c.slug                  as competition_slug,
  ps.fotmob_match_id,
  cm.match_slug
from public."Player_Scores" ps
left join public.competition_rounds cr  on cr.id = ps.competition_round_id
left join public.competitions c         on c.id = cr.competition_id
left join public.competition_matches cm on cm.id = ps.competition_match_id;
