-- ════════════════════════════════════════════════════════════════════════════
-- Competition & Auction Data Isolation — FULL MIGRATION (schema + backfill)
-- Context: docs/context/COMPETITION_AUCTION_DATA_ISOLATION.md
--
-- One-shot, idempotent, no edits required. Paste into the Supabase SQL Editor
-- and run. Safe to re-run. No data is dropped.
--
-- Auction mapping baked in:
--   World Cup 2026 = auctions 5, 6, 7   (competition 1)
--   EPL 2026/27    = auction 9          (competition 2; auction 8 is a test)
-- ════════════════════════════════════════════════════════════════════════════

-- ─── 1. Tables ──────────────────────────────────────────────────────────────
create table if not exists public.competitions (
  id           bigint generated by default as identity primary key,
  slug         text not null unique,
  name         text not null,
  status       text not null default 'active'
                 check (status in ('active', 'completed', 'archived')),
  archived_at  timestamptz,
  created_at   timestamptz not null default now()
);

create table if not exists public.competition_rounds (
  id                   bigint generated by default as identity primary key,
  competition_id       bigint not null references public.competitions(id) on delete cascade,
  round_slug           text   not null,
  display_name         text,
  round_number         integer,
  status               text   not null default 'open',
  is_active            boolean not null default false,
  legacy_game_week_id  bigint,
  created_at           timestamptz not null default now(),
  unique (competition_id, round_slug)
);
create index if not exists idx_competition_rounds_competition on public.competition_rounds (competition_id);
create index if not exists idx_competition_rounds_legacy_gw   on public.competition_rounds (legacy_game_week_id);

create table if not exists public.competition_matches (
  id               bigint generated by default as identity primary key,
  competition_id   bigint not null references public.competitions(id) on delete cascade,
  round_id         bigint not null references public.competition_rounds(id) on delete cascade,
  fotmob_match_id  bigint not null,
  match_slug       text,
  home_team        text,
  away_team        text,
  played_at        timestamptz,
  created_at       timestamptz not null default now(),
  unique (competition_id, fotmob_match_id)
);
create index if not exists idx_competition_matches_round on public.competition_matches (round_id);

create table if not exists public.competition_players (
  competition_id   bigint not null references public.competitions(id) on delete cascade,
  player_id        bigint not null,
  player_name      text,
  position         text,
  team_id          bigint,
  team_name        text,
  primary key (competition_id, player_id)
);

-- ─── 2. Columns on existing tables ──────────────────────────────────────────
alter table public."Auctions"
  add column if not exists competition_id bigint references public.competitions(id);
create index if not exists idx_auctions_competition on public."Auctions" (competition_id);

alter table public."Player_Scores"
  add column if not exists competition_round_id bigint references public.competition_rounds(id);
alter table public."Player_Scores"
  add column if not exists competition_match_id bigint references public.competition_matches(id);
alter table public."Player_Scores"
  add column if not exists fotmob_match_id bigint;
create index if not exists idx_player_scores_competition_round on public."Player_Scores" (competition_round_id);
create index if not exists idx_player_scores_fotmob_match      on public."Player_Scores" (fotmob_match_id);

-- ─── 3. Seed competitions ───────────────────────────────────────────────────
insert into public.competitions (id, slug, name, status, archived_at)
values
  (1, 'world-cup-2026',   'FIFA World Cup 2026',            'archived', now()),
  (2, 'epl-2026-27',      'English Premier League 2026/27', 'active',   null),
  (3, 'uefa-cl-2025-26',  'UEFA Champions League 2025/26',  'archived', now())
on conflict (slug) do nothing;

-- ─── 4. Seed rounds ─────────────────────────────────────────────────────────
insert into public.competition_rounds
  (id, competition_id, round_slug, display_name, round_number, status, is_active, legacy_game_week_id)
values
  (101, 2, 'mw01', 'Matchweek 1', 1, 'open', true, 100),
  (201, 3, 'ro16-leg2', 'Round of 16, Leg 2',    1, 'archived', false, 200),
  (202, 3, 'qf-leg1',   'Quarter-finals, Leg 1', 2, 'archived', false, 201),
  (203, 3, 'qf-leg2',   'Quarter-finals, Leg 2', 3, 'archived', false, 202),
  (204, 3, 'sf-leg1',   'Semi-finals, Leg 1',    4, 'archived', false, 203),
  (205, 3, 'sf-leg2',   'Semi-finals, Leg 2',    5, 'archived', false, 204)
on conflict (competition_id, round_slug) do nothing;

-- ─── 5. Seed matches (FotMob match IDs) ─────────────────────────────────────
insert into public.competition_matches
  (competition_id, round_id, fotmob_match_id, match_slug, home_team, away_team)
values
  (2, 101, 5795363, 'arsenal-coventry-city',            'Arsenal',            'Coventry City'),
  (2, 101, 5795364, 'hull-city-manchester-united',      'Hull City',          'Manchester United'),
  (2, 101, 5795365, 'everton-crystal-palace',           'Everton',            'Crystal Palace'),
  (2, 101, 5795366, 'ipswich-town-sunderland',          'Ipswich Town',       'Sunderland'),
  (2, 101, 5795367, 'nottingham-forest-leeds-united',   'Nottingham Forest',  'Leeds United'),
  (2, 101, 5795368, 'brentford-tottenham-hotspur',      'Brentford',          'Tottenham Hotspur'),
  (3, 201, 5205731, 'real-madrid-manchester-city',      'Real Madrid',        'Manchester City'),
  (3, 201, 5205734, 'barcelona-newcastle-united',       'Barcelona',          'Newcastle United'),
  (3, 201, 5205738, 'liverpool-galatasaray',            'Liverpool',          'Galatasaray'),
  (3, 201, 5205742, 'tottenham-hotspur-atletico-madrid','Tottenham Hotspur',  'Atletico Madrid'),
  (3, 202, 5205789, 'paris-saint-germain-liverpool',    'Paris Saint-Germain','Liverpool'),
  (3, 202, 5205791, 'real-madrid-bayern-munich',        'Real Madrid',        'Bayern Munich'),
  (3, 202, 5205793, 'barcelona-atletico-madrid',        'Barcelona',          'Atletico Madrid'),
  (3, 202, 5205795, 'sporting-cp-arsenal',              'Sporting CP',        'Arsenal'),
  (3, 203, 5205790, 'liverpool-paris-saint-germain',    'Liverpool',          'Paris Saint-Germain'),
  (3, 203, 5205792, 'bayern-munich-real-madrid',        'Bayern Munich',      'Real Madrid'),
  (3, 203, 5205794, 'atletico-madrid-barcelona',        'Atletico Madrid',    'Barcelona'),
  (3, 203, 5205796, 'arsenal-sporting-cp',              'Arsenal',            'Sporting CP'),
  (3, 204, 5205811, 'paris-saint-germain-bayern-munich','Paris Saint-Germain','Bayern Munich'),
  (3, 204, 5205813, 'atletico-madrid-arsenal',          'Atletico Madrid',    'Arsenal'),
  (3, 205, 5205812, 'bayern-munich-paris-saint-germain','Bayern Munich',      'Paris Saint-Germain'),
  (3, 205, 5205814, 'arsenal-atletico-madrid',          'Arsenal',            'Atletico Madrid')
on conflict (competition_id, fotmob_match_id) do nothing;

-- ─── 6. Attach auctions to competitions ─────────────────────────────────────
update public."Auctions" set competition_id = 1 where id in (5, 6, 7);  -- World Cup
update public."Auctions" set competition_id = 2 where id in (9);        -- EPL (8 is a test)

-- ─── 7. Populate competition_players for EPL from the global players pool ────
insert into public.competition_players
  (competition_id, player_id, player_name, position, team_id, team_name)
select
  2,
  p.player_id::bigint,
  p.player_name,
  p.position,
  nullif(p.team_id::text, '')::bigint,
  p.team_name
from public.players p
where p.player_id is not null
on conflict (competition_id, player_id) do update
  set player_name = excluded.player_name,
      position    = excluded.position,
      team_id     = excluded.team_id,
      team_name   = excluded.team_name;

-- ─── 8. Bridge EPL MW1 to the current active game_week_id ───────────────────
update public.competition_rounds
set legacy_game_week_id = (
  select id from public."Game_Weeks" where "Is_Active" = true limit 1
)
where id = 101;

-- ─── 9. Backfill competition_round_id on existing scores ────────────────────
update public."Player_Scores" ps
set competition_round_id = cr.id
from public.competition_rounds cr
where cr.legacy_game_week_id = ps.game_week_id
  and ps.competition_round_id is null;

-- ─── 10. Backfill match ID + competition_match_id (team match) ──────────────
update public."Player_Scores" ps
set competition_match_id = cm.id,
    fotmob_match_id      = cm.fotmob_match_id
from public.competition_rounds cr
join public.competition_players cp on cp.competition_id = cr.competition_id
join public.competition_matches cm
  on cm.round_id = cr.id
 and (cm.home_team = cp.team_name or cm.away_team = cp.team_name)
where ps.competition_round_id = cr.id
  and cp.player_id = ps.player_id
  and ps.competition_match_id is null;

-- ─── 11. Competition-safe unique key ────────────────────────────────────────
alter table public."Player_Scores"
  drop constraint if exists player_scores_round_player_unique;
alter table public."Player_Scores"
  add constraint player_scores_round_player_unique
  unique (competition_round_id, player_id);

-- ─── 12. Competition-aware upsert RPC (for future gameweeks) ────────────────
create or replace function public.upsert_player_scores_for_round(
  p_competition_round_id bigint,
  p_rows jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_upserted integer;
  v_legacy_gw bigint;
begin
  if p_competition_round_id is null then
    raise exception 'p_competition_round_id is required';
  end if;
  if p_rows is null or jsonb_typeof(p_rows) <> 'array' then
    raise exception 'p_rows must be a JSON array';
  end if;

  select legacy_game_week_id into v_legacy_gw
  from public.competition_rounds where id = p_competition_round_id;
  if v_legacy_gw is null then
    raise exception 'competition_round % has no legacy_game_week_id', p_competition_round_id;
  end if;

  insert into public."Player_Scores"
    (player_id, game_week_id, "Score", competition_round_id, competition_match_id, fotmob_match_id)
  select
    (r->>'player_id')::bigint,
    v_legacy_gw,
    (r->>'score')::numeric,
    p_competition_round_id,
    cm.id,
    (r->>'fotmob_match_id')::bigint
  from jsonb_array_elements(p_rows) as r
  left join public.competition_matches cm
    on cm.round_id = p_competition_round_id
   and cm.fotmob_match_id = (r->>'fotmob_match_id')::bigint
  where (r->>'player_id') is not null
    and (r->>'score') is not null
  on conflict (player_id, game_week_id)
  do update set
    "Score"              = excluded."Score",
    competition_round_id = excluded.competition_round_id,
    competition_match_id = excluded.competition_match_id,
    fotmob_match_id      = excluded.fotmob_match_id;

  get diagnostics v_upserted = row_count;
  return jsonb_build_object(
    'competition_round_id', p_competition_round_id,
    'legacy_game_week_id', v_legacy_gw,
    'upserted', v_upserted
  );
end;
$$;
grant execute on function public.upsert_player_scores_for_round(bigint, jsonb) to service_role;

-- ─── 13. Convenience view: scores joined to competition/round/match ─────────
create or replace view public.player_scores_scoped as
select
  ps.id,
  ps.player_id,
  ps."Score"              as score,
  ps.game_week_id,
  ps.competition_round_id,
  cr.round_slug,
  cr.competition_id,
  c.slug                  as competition_slug,
  ps.fotmob_match_id,
  cm.match_slug
from public."Player_Scores" ps
left join public.competition_rounds cr  on cr.id = ps.competition_round_id
left join public.competitions c         on c.id = cr.competition_id
left join public.competition_matches cm on cm.id = ps.competition_match_id;

-- ─── 14. Verify (read-only — check these after running) ─────────────────────
-- Unmapped scored rows (want 0 for the active competition):
select count(*) as unmapped_round from public."Player_Scores" where competition_round_id is null;
-- EPL rows missing a match tag (usually a team-name spelling mismatch):
select ps.player_id, ps.game_week_id
from public."Player_Scores" ps
where ps.competition_round_id = 101 and ps.competition_match_id is null;
-- Auction → competition attachment:
select id, name, competition_id from public."Auctions" order by id;
